"""Package real native approach evidence separately from concept/asset renders."""
import argparse,json,subprocess,shutil
from pathlib import Path
from PIL import Image,ImageDraw
p=argparse.ArgumentParser();p.add_argument('--capture',type=Path,required=True);p.add_argument('--baseline',type=Path,required=True);p.add_argument('--output',type=Path,required=True);a=p.parse_args();out=a.output.resolve();out.mkdir(parents=True,exist_ok=True);root=Path(__file__).resolve().parent
now=json.loads((a.capture/'preview.json').read_text());old=json.loads((a.baseline/'preview.json').read_text());assert now['complete']
shots=[]
for label,progress in [('reveal',.51),('approach',.56),('passing',.625)]:
 for kind,data,folder in [('new',now,a.capture),('before',old,a.baseline)]:
  f=min(data['frames'],key=lambda f:abs(f['progress']-progress));name=f'{label}-{kind}.jpg';Image.open(folder/f['file']).convert('RGB').save(out/name,quality=94)
  if kind=='new':shots.append(dict(label=label,progress=f['progress'],seconds=f['seconds'],source=f['file'],image=name))
(out/'shots.json').write_text(json.dumps(dict(buildGuid=now['buildGuid'],shots=shots),indent=2)+'\n')
strip=Image.new('RGB',(1920,390));draw=ImageDraw.Draw(strip)
for i,f in enumerate(shots):
 strip.paste(Image.open(out/f['image']).resize((640,360)),(i*640,0));draw.text((i*640+12,370),f"{f['label'].upper()} / ACTUAL GAMEPLAY / {f['seconds']:.1f}s",fill='white')
strip.save(out/'native-approach-strip.jpg',quality=95)
shutil.copyfile(root/'asset-review.png',out/'asset-render.png');shutil.copyfile(root/'scenario/concept/art.png',out/'concept.png')
subprocess.run(['ffmpeg','-y','-hide_banner','-loglevel','warning','-ss','20.3','-i',str(a.capture/'full-lap.mp4'),'-t','9.5','-c:v','libx264','-crf','18','-preset','fast','-c:a','aac','-movflags','+faststart',str(out/'turn-approach.mp4')],check=True)
(out/'index.html').write_text('''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Vector Rush · Koi Lantern turn</title><style>*{box-sizing:border-box}body{background:#0c1318;color:#edf0e9;font:16px system-ui;margin:0}main{max-width:1440px;padding:32px;margin:auto}h1{font-size:clamp(32px,4vw,56px);letter-spacing:-.04em;margin:.3em 0}p{line-height:1.6;color:#b6c5c8;max-width:950px}.eyebrow{font-size:12px;color:#e6b66b;letter-spacing:.16em}video,img{width:100%;display:block}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}figure{margin:0;background:#152128}figcaption{padding:14px}h2{margin-top:36px;font-size:24px}details{margin-top:32px}summary{cursor:pointer;padding:18px;background:#17222a}.note{font-size:13px}a{color:#e7ba78}@media(max-width:700px){main{padding:16px}.grid{grid-template-columns:1fr}}</style><main><div class="eyebrow">VECTOR RUSH / ONE TURN, ONE NEW LANDMARK</div><h1>A focal point beyond the bend.</h1><p>The new Koi Lantern Tower appears ahead as you enter the sweeping outdoor turn, grows through the approach, and moves to the right as you pass. This is the actual standalone game, with the existing road, ship, HUD and handling.</p><video controls preload="auto" poster="approach-new.jpg" src="turn-approach.mp4" aria-label="Native driving through the Koi Lantern turn"></video><button style="margin-top:12px;padding:12px 20px;background:#dba55d;color:#111;border:0;border-radius:6px;cursor:pointer;font:inherit" onclick="document.querySelector('video').play()">Play turn replay</button><p class="note">9.5-second native excerpt with game audio and automated steering. Video timing follows the capture; it is not a performance benchmark.</p><h2>Before / with the landmark</h2><div class="grid"><figure><img src="approach-before.jpg" alt="Earlier Stage 8 bend without the koi landmark"><figcaption>Before — Stage 8</figcaption></figure><figure><img src="approach-new.jpg" alt="Stage 9 driving view with the koi and amber ring ahead"><figcaption>With the new landmark — Stage 9</figcaption></figure></div><h2>Reveal → approach → passing</h2><img src="native-approach-strip.jpg" alt="Three actual driving frames showing the landmark approaching and moving aside"><details><summary>New asset and its concept reference</summary><div class="grid"><figure><img src="asset-render.png" alt="Blender render of the new modeled koi tower"><figcaption>Actual authored 3D asset · Blender render, not gameplay</figcaption></figure><figure><img src="concept.png" alt="Scenario generated design reference"><figcaption>Scenario concept reference · not gameplay</figcaption></figure></div></details><p class="note">One landmark trial. Owner visual review and manual driving remain open. No other proposed landmark has been added.</p></main></html>''')
print(out/'index.html')
